/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as ScheduleCallRouteImport } from './routes/schedule-call'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HipaaComplianceRouteImport } from './routes/hipaa-compliance'
import { Route as BookADemoRouteImport } from './routes/book-a-demo'
import { Route as IndexRouteImport } from './routes/index'

const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleCallRoute = ScheduleCallRouteImport.update({
  id: '/schedule-call',
  path: '/schedule-call',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HipaaComplianceRoute = HipaaComplianceRouteImport.update({
  id: '/hipaa-compliance',
  path: '/hipaa-compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const BookADemoRoute = BookADemoRouteImport.update({
  id: '/book-a-demo',
  path: '/book-a-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-a-demo': typeof BookADemoRoute
  '/hipaa-compliance': typeof HipaaComplianceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/schedule-call': typeof ScheduleCallRoute
  '/terms-conditions': typeof TermsConditionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-a-demo': typeof BookADemoRoute
  '/hipaa-compliance': typeof HipaaComplianceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/schedule-call': typeof ScheduleCallRoute
  '/terms-conditions': typeof TermsConditionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-a-demo': typeof BookADemoRoute
  '/hipaa-compliance': typeof HipaaComplianceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/schedule-call': typeof ScheduleCallRoute
  '/terms-conditions': typeof TermsConditionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book-a-demo'
    | '/hipaa-compliance'
    | '/privacy-policy'
    | '/schedule-call'
    | '/terms-conditions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book-a-demo'
    | '/hipaa-compliance'
    | '/privacy-policy'
    | '/schedule-call'
    | '/terms-conditions'
  id:
    | '__root__'
    | '/'
    | '/book-a-demo'
    | '/hipaa-compliance'
    | '/privacy-policy'
    | '/schedule-call'
    | '/terms-conditions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookADemoRoute: typeof BookADemoRoute
  HipaaComplianceRoute: typeof HipaaComplianceRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ScheduleCallRoute: typeof ScheduleCallRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule-call': {
      id: '/schedule-call'
      path: '/schedule-call'
      fullPath: '/schedule-call'
      preLoaderRoute: typeof ScheduleCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hipaa-compliance': {
      id: '/hipaa-compliance'
      path: '/hipaa-compliance'
      fullPath: '/hipaa-compliance'
      preLoaderRoute: typeof HipaaComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-demo': {
      id: '/book-a-demo'
      path: '/book-a-demo'
      fullPath: '/book-a-demo'
      preLoaderRoute: typeof BookADemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookADemoRoute: BookADemoRoute,
  HipaaComplianceRoute: HipaaComplianceRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ScheduleCallRoute: ScheduleCallRoute,
  TermsConditionsRoute: TermsConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
